services:
  client:
    build: .
    container_name: hero-app
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - frontend-network

networks:
  frontend-network:
    external: true
